//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.ParksServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ParksServiceReference.IParkService")]
    public interface IParkService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkService/GetDataWithoutDB", ReplyAction="http://tempuri.org/IParkService/GetDataWithoutDBResponse")]
        System.Data.DataSet GetDataWithoutDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkService/GetDataWithoutDB", ReplyAction="http://tempuri.org/IParkService/GetDataWithoutDBResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataWithoutDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkService/GetParksFromDBWithOutConfig", ReplyAction="http://tempuri.org/IParkService/GetParksFromDBWithOutConfigResponse")]
        System.Data.DataSet GetParksFromDBWithOutConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkService/GetParksFromDBWithOutConfig", ReplyAction="http://tempuri.org/IParkService/GetParksFromDBWithOutConfigResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetParksFromDBWithOutConfigAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkService/GetParksFromDBWithConfig", ReplyAction="http://tempuri.org/IParkService/GetParksFromDBWithConfigResponse")]
        System.Data.DataSet GetParksFromDBWithConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParkService/GetParksFromDBWithConfig", ReplyAction="http://tempuri.org/IParkService/GetParksFromDBWithConfigResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetParksFromDBWithConfigAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IParkServiceChannel : Business.ParksServiceReference.IParkService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParkServiceClient : System.ServiceModel.ClientBase<Business.ParksServiceReference.IParkService>, Business.ParksServiceReference.IParkService {
        
        public ParkServiceClient() {
        }
        
        public ParkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDataWithoutDB() {
            return base.Channel.GetDataWithoutDB();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataWithoutDBAsync() {
            return base.Channel.GetDataWithoutDBAsync();
        }
        
        public System.Data.DataSet GetParksFromDBWithOutConfig() {
            return base.Channel.GetParksFromDBWithOutConfig();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetParksFromDBWithOutConfigAsync() {
            return base.Channel.GetParksFromDBWithOutConfigAsync();
        }
        
        public System.Data.DataSet GetParksFromDBWithConfig() {
            return base.Channel.GetParksFromDBWithConfig();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetParksFromDBWithConfigAsync() {
            return base.Channel.GetParksFromDBWithConfigAsync();
        }
    }
}
